#!/usr/bin/env bash

ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Subcutaneous.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adipose_Visceral_Omentum.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Adrenal_Gland.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Aorta.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Coronary.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Artery_Tibial.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Amygdala.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Anterior_cingulate_cortex_BA24.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Caudate_basal_ganglia.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellar_Hemisphere.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cerebellum.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Cortex.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Frontal_Cortex_BA9.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hippocampus.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Hypothalamus.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Nucleus_accumbens_basal_ganglia.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Putamen_basal_ganglia.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Spinal_cord_cervical_c-1.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Brain_Substantia_nigra.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Breast_Mammary_Tissue.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_Cultured_fibroblasts.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Cells_EBV-transformed_lymphocytes.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Sigmoid.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Colon_Transverse.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Gastroesophageal_Junction.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Mucosa.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Esophagus_Muscularis.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Atrial_Appendage.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Heart_Left_Ventricle.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Kidney_Cortex.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Liver.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Lung.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Minor_Salivary_Gland.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Muscle_Skeletal.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Nerve_Tibial.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Ovary.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pancreas.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Pituitary.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Prostate.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.cluster_correlations.txt.gz Skin_Not_Sun_Exposed_Suprapubic.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.clusters.txt.gz Skin_Not_Sun_Exposed_Suprapubic.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.model_summary.txt.gz Skin_Not_Sun_Exposed_Suprapubic.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.models.txt.gz Skin_Not_Sun_Exposed_Suprapubic.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.models_variants.txt.gz Skin_Not_Sun_Exposed_Suprapubic.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Not_Sun_Exposed.variants_pip.txt.gz Skin_Not_Sun_Exposed_Suprapubic.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.cluster_correlations.txt.gz Skin_Not_Sun_Exposed_Lower_leg.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.clusters.txt.gz Skin_Sun_Exposed_Lower_leg.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.model_summary.txt.gz Skin_Sun_Exposed_Lower_leg.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.models.txt.gz Skin_Sun_Exposed_Lower_leg.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.models_variants.txt.gz Skin_Sun_Exposed_Lower_leg.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Skin_Sun_Exposed.variants_pip.txt.gz Skin_Sun_Exposed_Lower_leg.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Small_Intestine_Terminal_Ileum.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Spleen.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Stomach.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Testis.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Thyroid.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Uterus.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Vagina.variants_pip.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.cluster_correlations.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.clusters.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.model_summary.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.models.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.models_variants.txt.gz
ln -s /gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/dapg/eqtl/parsed_dapg_misnamed/Whole_Blood.variants_pip.txt.gz