#!/bin/bash

[ -d data/dapg_parsed/sqtl ] || mkdir -p data/dapg_parsed/sqtl
cd data/dapg_parsed/sqtl
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Adipose_Subcutaneous.cluster_correlations.txt.gz -o Adipose_Subcutaneous.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Adipose_Subcutaneous.clusters.txt.gz -o Adipose_Subcutaneous.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Adipose_Subcutaneous.model_summary.txt.gz -o Adipose_Subcutaneous.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Adipose_Subcutaneous.models.txt.gz -o Adipose_Subcutaneous.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Adipose_Subcutaneous.models_variants.txt.gz -o Adipose_Subcutaneous.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Adipose_Subcutaneous.variants_pip.txt.gz -o Adipose_Subcutaneous.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Adipose_Visceral_Omentum.cluster_correlations.txt.gz -o Adipose_Visceral_Omentum.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Adipose_Visceral_Omentum.clusters.txt.gz -o Adipose_Visceral_Omentum.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Adipose_Visceral_Omentum.model_summary.txt.gz -o Adipose_Visceral_Omentum.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Adipose_Visceral_Omentum.models.txt.gz -o Adipose_Visceral_Omentum.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Adipose_Visceral_Omentum.models_variants.txt.gz -o Adipose_Visceral_Omentum.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Adipose_Visceral_Omentum.variants_pip.txt.gz -o Adipose_Visceral_Omentum.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Adrenal_Gland.cluster_correlations.txt.gz -o Adrenal_Gland.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Adrenal_Gland.clusters.txt.gz -o Adrenal_Gland.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Adrenal_Gland.model_summary.txt.gz -o Adrenal_Gland.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Adrenal_Gland.models.txt.gz -o Adrenal_Gland.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Adrenal_Gland.models_variants.txt.gz -o Adrenal_Gland.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Adrenal_Gland.variants_pip.txt.gz -o Adrenal_Gland.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Artery_Aorta.cluster_correlations.txt.gz -o Artery_Aorta.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Artery_Aorta.clusters.txt.gz -o Artery_Aorta.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Artery_Aorta.model_summary.txt.gz -o Artery_Aorta.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Artery_Aorta.models.txt.gz -o Artery_Aorta.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Artery_Aorta.models_variants.txt.gz -o Artery_Aorta.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Artery_Aorta.variants_pip.txt.gz -o Artery_Aorta.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Artery_Coronary.cluster_correlations.txt.gz -o Artery_Coronary.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Artery_Coronary.clusters.txt.gz -o Artery_Coronary.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Artery_Coronary.model_summary.txt.gz -o Artery_Coronary.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Artery_Coronary.models.txt.gz -o Artery_Coronary.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Artery_Coronary.models_variants.txt.gz -o Artery_Coronary.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Artery_Coronary.variants_pip.txt.gz -o Artery_Coronary.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Artery_Tibial.cluster_correlations.txt.gz -o Artery_Tibial.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Artery_Tibial.clusters.txt.gz -o Artery_Tibial.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Artery_Tibial.model_summary.txt.gz -o Artery_Tibial.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Artery_Tibial.models.txt.gz -o Artery_Tibial.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Artery_Tibial.models_variants.txt.gz -o Artery_Tibial.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Artery_Tibial.variants_pip.txt.gz -o Artery_Tibial.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Amygdala.cluster_correlations.txt.gz -o Brain_Amygdala.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Amygdala.clusters.txt.gz -o Brain_Amygdala.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Amygdala.model_summary.txt.gz -o Brain_Amygdala.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Amygdala.models.txt.gz -o Brain_Amygdala.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Amygdala.models_variants.txt.gz -o Brain_Amygdala.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Amygdala.variants_pip.txt.gz -o Brain_Amygdala.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Anterior_cingulate_cortex_BA24.cluster_correlations.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Anterior_cingulate_cortex_BA24.clusters.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Anterior_cingulate_cortex_BA24.model_summary.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Anterior_cingulate_cortex_BA24.models.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Anterior_cingulate_cortex_BA24.models_variants.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Anterior_cingulate_cortex_BA24.variants_pip.txt.gz -o Brain_Anterior_cingulate_cortex_BA24.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Caudate_basal_ganglia.cluster_correlations.txt.gz -o Brain_Caudate_basal_ganglia.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Caudate_basal_ganglia.clusters.txt.gz -o Brain_Caudate_basal_ganglia.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Caudate_basal_ganglia.model_summary.txt.gz -o Brain_Caudate_basal_ganglia.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Caudate_basal_ganglia.models.txt.gz -o Brain_Caudate_basal_ganglia.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Caudate_basal_ganglia.models_variants.txt.gz -o Brain_Caudate_basal_ganglia.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Caudate_basal_ganglia.variants_pip.txt.gz -o Brain_Caudate_basal_ganglia.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Cerebellar_Hemisphere.cluster_correlations.txt.gz -o Brain_Cerebellar_Hemisphere.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Cerebellar_Hemisphere.clusters.txt.gz -o Brain_Cerebellar_Hemisphere.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Cerebellar_Hemisphere.model_summary.txt.gz -o Brain_Cerebellar_Hemisphere.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Cerebellar_Hemisphere.models.txt.gz -o Brain_Cerebellar_Hemisphere.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Cerebellar_Hemisphere.models_variants.txt.gz -o Brain_Cerebellar_Hemisphere.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Cerebellar_Hemisphere.variants_pip.txt.gz -o Brain_Cerebellar_Hemisphere.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Cerebellum.cluster_correlations.txt.gz -o Brain_Cerebellum.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Cerebellum.clusters.txt.gz -o Brain_Cerebellum.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Cerebellum.model_summary.txt.gz -o Brain_Cerebellum.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Cerebellum.models.txt.gz -o Brain_Cerebellum.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Cerebellum.models_variants.txt.gz -o Brain_Cerebellum.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Cerebellum.variants_pip.txt.gz -o Brain_Cerebellum.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Cortex.cluster_correlations.txt.gz -o Brain_Cortex.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Cortex.clusters.txt.gz -o Brain_Cortex.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Cortex.model_summary.txt.gz -o Brain_Cortex.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Cortex.models.txt.gz -o Brain_Cortex.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Cortex.models_variants.txt.gz -o Brain_Cortex.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Cortex.variants_pip.txt.gz -o Brain_Cortex.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Frontal_Cortex_BA9.cluster_correlations.txt.gz -o Brain_Frontal_Cortex_BA9.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Frontal_Cortex_BA9.clusters.txt.gz -o Brain_Frontal_Cortex_BA9.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Frontal_Cortex_BA9.model_summary.txt.gz -o Brain_Frontal_Cortex_BA9.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Frontal_Cortex_BA9.models.txt.gz -o Brain_Frontal_Cortex_BA9.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Frontal_Cortex_BA9.models_variants.txt.gz -o Brain_Frontal_Cortex_BA9.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Frontal_Cortex_BA9.variants_pip.txt.gz -o Brain_Frontal_Cortex_BA9.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Hippocampus.cluster_correlations.txt.gz -o Brain_Hippocampus.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Hippocampus.clusters.txt.gz -o Brain_Hippocampus.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Hippocampus.model_summary.txt.gz -o Brain_Hippocampus.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Hippocampus.models.txt.gz -o Brain_Hippocampus.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Hippocampus.models_variants.txt.gz -o Brain_Hippocampus.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Hippocampus.variants_pip.txt.gz -o Brain_Hippocampus.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Hypothalamus.cluster_correlations.txt.gz -o Brain_Hypothalamus.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Hypothalamus.clusters.txt.gz -o Brain_Hypothalamus.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Hypothalamus.model_summary.txt.gz -o Brain_Hypothalamus.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Hypothalamus.models.txt.gz -o Brain_Hypothalamus.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Hypothalamus.models_variants.txt.gz -o Brain_Hypothalamus.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Hypothalamus.variants_pip.txt.gz -o Brain_Hypothalamus.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Nucleus_accumbens_basal_ganglia.cluster_correlations.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Nucleus_accumbens_basal_ganglia.clusters.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Nucleus_accumbens_basal_ganglia.model_summary.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Nucleus_accumbens_basal_ganglia.models.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Nucleus_accumbens_basal_ganglia.models_variants.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Nucleus_accumbens_basal_ganglia.variants_pip.txt.gz -o Brain_Nucleus_accumbens_basal_ganglia.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Putamen_basal_ganglia.cluster_correlations.txt.gz -o Brain_Putamen_basal_ganglia.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Putamen_basal_ganglia.clusters.txt.gz -o Brain_Putamen_basal_ganglia.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Putamen_basal_ganglia.model_summary.txt.gz -o Brain_Putamen_basal_ganglia.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Putamen_basal_ganglia.models.txt.gz -o Brain_Putamen_basal_ganglia.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Putamen_basal_ganglia.models_variants.txt.gz -o Brain_Putamen_basal_ganglia.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Putamen_basal_ganglia.variants_pip.txt.gz -o Brain_Putamen_basal_ganglia.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Spinal_cord_cervical_c-1.cluster_correlations.txt.gz -o Brain_Spinal_cord_cervical_c-1.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Spinal_cord_cervical_c-1.clusters.txt.gz -o Brain_Spinal_cord_cervical_c-1.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Spinal_cord_cervical_c-1.model_summary.txt.gz -o Brain_Spinal_cord_cervical_c-1.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Spinal_cord_cervical_c-1.models.txt.gz -o Brain_Spinal_cord_cervical_c-1.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Spinal_cord_cervical_c-1.models_variants.txt.gz -o Brain_Spinal_cord_cervical_c-1.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Spinal_cord_cervical_c-1.variants_pip.txt.gz -o Brain_Spinal_cord_cervical_c-1.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Brain_Substantia_nigra.cluster_correlations.txt.gz -o Brain_Substantia_nigra.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Brain_Substantia_nigra.clusters.txt.gz -o Brain_Substantia_nigra.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Brain_Substantia_nigra.model_summary.txt.gz -o Brain_Substantia_nigra.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Brain_Substantia_nigra.models.txt.gz -o Brain_Substantia_nigra.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Brain_Substantia_nigra.models_variants.txt.gz -o Brain_Substantia_nigra.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Brain_Substantia_nigra.variants_pip.txt.gz -o Brain_Substantia_nigra.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Breast_Mammary_Tissue.cluster_correlations.txt.gz -o Breast_Mammary_Tissue.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Breast_Mammary_Tissue.clusters.txt.gz -o Breast_Mammary_Tissue.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Breast_Mammary_Tissue.model_summary.txt.gz -o Breast_Mammary_Tissue.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Breast_Mammary_Tissue.models.txt.gz -o Breast_Mammary_Tissue.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Breast_Mammary_Tissue.models_variants.txt.gz -o Breast_Mammary_Tissue.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Breast_Mammary_Tissue.variants_pip.txt.gz -o Breast_Mammary_Tissue.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Cells_Cultured_fibroblasts.cluster_correlations.txt.gz -o Cells_Cultured_fibroblasts.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Cells_Cultured_fibroblasts.clusters.txt.gz -o Cells_Cultured_fibroblasts.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Cells_Cultured_fibroblasts.model_summary.txt.gz -o Cells_Cultured_fibroblasts.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Cells_Cultured_fibroblasts.models.txt.gz -o Cells_Cultured_fibroblasts.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Cells_Cultured_fibroblasts.models_variants.txt.gz -o Cells_Cultured_fibroblasts.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Cells_Cultured_fibroblasts.variants_pip.txt.gz -o Cells_Cultured_fibroblasts.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Cells_EBV-transformed_lymphocytes.cluster_correlations.txt.gz -o Cells_EBV-transformed_lymphocytes.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Cells_EBV-transformed_lymphocytes.clusters.txt.gz -o Cells_EBV-transformed_lymphocytes.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Cells_EBV-transformed_lymphocytes.model_summary.txt.gz -o Cells_EBV-transformed_lymphocytes.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Cells_EBV-transformed_lymphocytes.models.txt.gz -o Cells_EBV-transformed_lymphocytes.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Cells_EBV-transformed_lymphocytes.models_variants.txt.gz -o Cells_EBV-transformed_lymphocytes.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Cells_EBV-transformed_lymphocytes.variants_pip.txt.gz -o Cells_EBV-transformed_lymphocytes.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Colon_Sigmoid.cluster_correlations.txt.gz -o Colon_Sigmoid.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Colon_Sigmoid.clusters.txt.gz -o Colon_Sigmoid.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Colon_Sigmoid.model_summary.txt.gz -o Colon_Sigmoid.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Colon_Sigmoid.models.txt.gz -o Colon_Sigmoid.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Colon_Sigmoid.models_variants.txt.gz -o Colon_Sigmoid.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Colon_Sigmoid.variants_pip.txt.gz -o Colon_Sigmoid.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Colon_Transverse.cluster_correlations.txt.gz -o Colon_Transverse.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Colon_Transverse.clusters.txt.gz -o Colon_Transverse.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Colon_Transverse.model_summary.txt.gz -o Colon_Transverse.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Colon_Transverse.models.txt.gz -o Colon_Transverse.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Colon_Transverse.models_variants.txt.gz -o Colon_Transverse.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Colon_Transverse.variants_pip.txt.gz -o Colon_Transverse.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Esophagus_Gastroesophageal_Junction.cluster_correlations.txt.gz -o Esophagus_Gastroesophageal_Junction.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Esophagus_Gastroesophageal_Junction.clusters.txt.gz -o Esophagus_Gastroesophageal_Junction.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Esophagus_Gastroesophageal_Junction.model_summary.txt.gz -o Esophagus_Gastroesophageal_Junction.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Esophagus_Gastroesophageal_Junction.models.txt.gz -o Esophagus_Gastroesophageal_Junction.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Esophagus_Gastroesophageal_Junction.models_variants.txt.gz -o Esophagus_Gastroesophageal_Junction.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Esophagus_Gastroesophageal_Junction.variants_pip.txt.gz -o Esophagus_Gastroesophageal_Junction.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Esophagus_Mucosa.cluster_correlations.txt.gz -o Esophagus_Mucosa.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Esophagus_Mucosa.clusters.txt.gz -o Esophagus_Mucosa.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Esophagus_Mucosa.model_summary.txt.gz -o Esophagus_Mucosa.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Esophagus_Mucosa.models.txt.gz -o Esophagus_Mucosa.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Esophagus_Mucosa.models_variants.txt.gz -o Esophagus_Mucosa.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Esophagus_Mucosa.variants_pip.txt.gz -o Esophagus_Mucosa.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Esophagus_Muscularis.cluster_correlations.txt.gz -o Esophagus_Muscularis.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Esophagus_Muscularis.clusters.txt.gz -o Esophagus_Muscularis.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Esophagus_Muscularis.model_summary.txt.gz -o Esophagus_Muscularis.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Esophagus_Muscularis.models.txt.gz -o Esophagus_Muscularis.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Esophagus_Muscularis.models_variants.txt.gz -o Esophagus_Muscularis.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Esophagus_Muscularis.variants_pip.txt.gz -o Esophagus_Muscularis.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Heart_Atrial_Appendage.cluster_correlations.txt.gz -o Heart_Atrial_Appendage.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Heart_Atrial_Appendage.clusters.txt.gz -o Heart_Atrial_Appendage.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Heart_Atrial_Appendage.model_summary.txt.gz -o Heart_Atrial_Appendage.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Heart_Atrial_Appendage.models.txt.gz -o Heart_Atrial_Appendage.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Heart_Atrial_Appendage.models_variants.txt.gz -o Heart_Atrial_Appendage.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Heart_Atrial_Appendage.variants_pip.txt.gz -o Heart_Atrial_Appendage.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Heart_Left_Ventricle.cluster_correlations.txt.gz -o Heart_Left_Ventricle.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Heart_Left_Ventricle.clusters.txt.gz -o Heart_Left_Ventricle.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Heart_Left_Ventricle.model_summary.txt.gz -o Heart_Left_Ventricle.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Heart_Left_Ventricle.models.txt.gz -o Heart_Left_Ventricle.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Heart_Left_Ventricle.models_variants.txt.gz -o Heart_Left_Ventricle.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Heart_Left_Ventricle.variants_pip.txt.gz -o Heart_Left_Ventricle.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Kidney_Cortex.cluster_correlations.txt.gz -o Kidney_Cortex.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Kidney_Cortex.clusters.txt.gz -o Kidney_Cortex.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Kidney_Cortex.model_summary.txt.gz -o Kidney_Cortex.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Kidney_Cortex.models.txt.gz -o Kidney_Cortex.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Kidney_Cortex.models_variants.txt.gz -o Kidney_Cortex.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Kidney_Cortex.variants_pip.txt.gz -o Kidney_Cortex.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Liver.cluster_correlations.txt.gz -o Liver.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Liver.clusters.txt.gz -o Liver.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Liver.model_summary.txt.gz -o Liver.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Liver.models.txt.gz -o Liver.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Liver.models_variants.txt.gz -o Liver.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Liver.variants_pip.txt.gz -o Liver.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Lung.cluster_correlations.txt.gz -o Lung.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Lung.clusters.txt.gz -o Lung.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Lung.model_summary.txt.gz -o Lung.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Lung.models.txt.gz -o Lung.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Lung.models_variants.txt.gz -o Lung.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Lung.variants_pip.txt.gz -o Lung.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Minor_Salivary_Gland.cluster_correlations.txt.gz -o Minor_Salivary_Gland.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Minor_Salivary_Gland.clusters.txt.gz -o Minor_Salivary_Gland.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Minor_Salivary_Gland.model_summary.txt.gz -o Minor_Salivary_Gland.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Minor_Salivary_Gland.models.txt.gz -o Minor_Salivary_Gland.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Minor_Salivary_Gland.models_variants.txt.gz -o Minor_Salivary_Gland.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Minor_Salivary_Gland.variants_pip.txt.gz -o Minor_Salivary_Gland.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Muscle_Skeletal.cluster_correlations.txt.gz -o Muscle_Skeletal.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Muscle_Skeletal.clusters.txt.gz -o Muscle_Skeletal.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Muscle_Skeletal.model_summary.txt.gz -o Muscle_Skeletal.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Muscle_Skeletal.models.txt.gz -o Muscle_Skeletal.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Muscle_Skeletal.models_variants.txt.gz -o Muscle_Skeletal.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Muscle_Skeletal.variants_pip.txt.gz -o Muscle_Skeletal.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Nerve_Tibial.cluster_correlations.txt.gz -o Nerve_Tibial.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Nerve_Tibial.clusters.txt.gz -o Nerve_Tibial.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Nerve_Tibial.model_summary.txt.gz -o Nerve_Tibial.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Nerve_Tibial.models.txt.gz -o Nerve_Tibial.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Nerve_Tibial.models_variants.txt.gz -o Nerve_Tibial.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Nerve_Tibial.variants_pip.txt.gz -o Nerve_Tibial.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Ovary.cluster_correlations.txt.gz -o Ovary.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Ovary.clusters.txt.gz -o Ovary.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Ovary.model_summary.txt.gz -o Ovary.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Ovary.models.txt.gz -o Ovary.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Ovary.models_variants.txt.gz -o Ovary.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Ovary.variants_pip.txt.gz -o Ovary.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Pancreas.cluster_correlations.txt.gz -o Pancreas.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Pancreas.clusters.txt.gz -o Pancreas.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Pancreas.model_summary.txt.gz -o Pancreas.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Pancreas.models.txt.gz -o Pancreas.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Pancreas.models_variants.txt.gz -o Pancreas.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Pancreas.variants_pip.txt.gz -o Pancreas.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Pituitary.cluster_correlations.txt.gz -o Pituitary.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Pituitary.clusters.txt.gz -o Pituitary.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Pituitary.model_summary.txt.gz -o Pituitary.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Pituitary.models.txt.gz -o Pituitary.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Pituitary.models_variants.txt.gz -o Pituitary.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Pituitary.variants_pip.txt.gz -o Pituitary.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Prostate.cluster_correlations.txt.gz -o Prostate.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Prostate.clusters.txt.gz -o Prostate.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Prostate.model_summary.txt.gz -o Prostate.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Prostate.models.txt.gz -o Prostate.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Prostate.models_variants.txt.gz -o Prostate.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Prostate.variants_pip.txt.gz -o Prostate.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Skin_Not_Sun_Exposed_Suprapubic.cluster_correlations.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Skin_Not_Sun_Exposed_Suprapubic.clusters.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Skin_Not_Sun_Exposed_Suprapubic.model_summary.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Skin_Not_Sun_Exposed_Suprapubic.models.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Skin_Not_Sun_Exposed_Suprapubic.models_variants.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Skin_Not_Sun_Exposed_Suprapubic.variants_pip.txt.gz -o Skin_Not_Sun_Exposed_Suprapubic.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Skin_Sun_Exposed_Lower_leg.cluster_correlations.txt.gz -o Skin_Sun_Exposed_Lower_leg.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Skin_Sun_Exposed_Lower_leg.clusters.txt.gz -o Skin_Sun_Exposed_Lower_leg.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Skin_Sun_Exposed_Lower_leg.model_summary.txt.gz -o Skin_Sun_Exposed_Lower_leg.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Skin_Sun_Exposed_Lower_leg.models.txt.gz -o Skin_Sun_Exposed_Lower_leg.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Skin_Sun_Exposed_Lower_leg.models_variants.txt.gz -o Skin_Sun_Exposed_Lower_leg.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Skin_Sun_Exposed_Lower_leg.variants_pip.txt.gz -o Skin_Sun_Exposed_Lower_leg.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Small_Intestine_Terminal_Ileum.cluster_correlations.txt.gz -o Small_Intestine_Terminal_Ileum.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Small_Intestine_Terminal_Ileum.clusters.txt.gz -o Small_Intestine_Terminal_Ileum.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Small_Intestine_Terminal_Ileum.model_summary.txt.gz -o Small_Intestine_Terminal_Ileum.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Small_Intestine_Terminal_Ileum.models.txt.gz -o Small_Intestine_Terminal_Ileum.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Small_Intestine_Terminal_Ileum.models_variants.txt.gz -o Small_Intestine_Terminal_Ileum.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Small_Intestine_Terminal_Ileum.variants_pip.txt.gz -o Small_Intestine_Terminal_Ileum.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Spleen.cluster_correlations.txt.gz -o Spleen.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Spleen.clusters.txt.gz -o Spleen.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Spleen.model_summary.txt.gz -o Spleen.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Spleen.models.txt.gz -o Spleen.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Spleen.models_variants.txt.gz -o Spleen.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Spleen.variants_pip.txt.gz -o Spleen.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Stomach.cluster_correlations.txt.gz -o Stomach.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Stomach.clusters.txt.gz -o Stomach.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Stomach.model_summary.txt.gz -o Stomach.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Stomach.models.txt.gz -o Stomach.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Stomach.models_variants.txt.gz -o Stomach.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Stomach.variants_pip.txt.gz -o Stomach.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Testis.cluster_correlations.txt.gz -o Testis.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Testis.clusters.txt.gz -o Testis.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Testis.model_summary.txt.gz -o Testis.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Testis.models.txt.gz -o Testis.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Testis.models_variants.txt.gz -o Testis.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Testis.variants_pip.txt.gz -o Testis.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Thyroid.cluster_correlations.txt.gz -o Thyroid.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Thyroid.clusters.txt.gz -o Thyroid.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Thyroid.model_summary.txt.gz -o Thyroid.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Thyroid.models.txt.gz -o Thyroid.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Thyroid.models_variants.txt.gz -o Thyroid.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Thyroid.variants_pip.txt.gz -o Thyroid.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Uterus.cluster_correlations.txt.gz -o Uterus.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Uterus.clusters.txt.gz -o Uterus.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Uterus.model_summary.txt.gz -o Uterus.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Uterus.models.txt.gz -o Uterus.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Uterus.models_variants.txt.gz -o Uterus.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Uterus.variants_pip.txt.gz -o Uterus.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Vagina.cluster_correlations.txt.gz -o Vagina.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Vagina.clusters.txt.gz -o Vagina.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Vagina.model_summary.txt.gz -o Vagina.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Vagina.models.txt.gz -o Vagina.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Vagina.models_variants.txt.gz -o Vagina.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Vagina.variants_pip.txt.gz -o Vagina.variants_pip.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/cluster_correlations/Whole_Blood.cluster_correlations.txt.gz -o Whole_Blood.cluster_correlations.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/clusters/Whole_Blood.clusters.txt.gz -o Whole_Blood.clusters.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/model_summary/Whole_Blood.model_summary.txt.gz -o Whole_Blood.model_summary.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models/Whole_Blood.models.txt.gz -o Whole_Blood.models.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/models_variants/Whole_Blood.models_variants.txt.gz -o Whole_Blood.models_variants.txt.gz
curl https://storage.googleapis.com/gtex-gwas-share/dapg_parsed/sqtl/variants_pip/Whole_Blood.variants_pip.txt.gz -o Whole_Blood.variants_pip.txt.gz

cd ../../..
